### ISSUE TITLE
Pick User information from Keybase

### ISSUE THREAD

**Issue by upgoingstar** [DataSploit/datasploit#126]
As suggested by @anantshri, pick verified information from Keybase.

https://keybase.io/_/api/1.0/user/lookup.json?usernames=XXXX

Easy Peasy :D

**Comment by 0xbadshah** [comment]
I had this idea long back. I created a script to accomplish that. Check it out at: https://github.com/Chan9390/Misc-Scripts/blob/master/keybase.py

But what I felt was, **it would be better if there was inter-relation of data** between different modules of Datasploit, so that this script could be easily integrated. The current structure to find username in Datasploit is limited and only does GitHub user analysis. I would suggest you to modularize the username module i.e. *one function/file to be responsible for gathering info from each site*. In that case, keybase script could be used to get the twitter, facebook, reddit etc accounts of the target, after which the usernames could be updated and running username-fetching functions is not required.

BTW @anantshri has updated most of his social links on Keybase, which from a friend point of view is good, but from OSINT point of view is a security risk. :smile:

**Comment by upgoingstar** [comment]
solved in https://github.com/DataSploit/datasploit/commit/1160e5f963daeeda5e32308770dce2780c9c6c49
