### ISSUE TITLE
where to find the GUI 

### ISSUE THREAD

**Issue by parrotcartot** [DataSploit/datasploit#45]
Hey guys, 

i desperately searched for the GUI in the tool : /, but I couldnt find it.. Is it already out there? At least it says its available in GUI and console.

If not, where can I access or export the results of the tool?

would be glad for some advice, thanks!

**Comment by 0xbadshah** [comment]
As of now there is no GUI for the tool. The results _could not be exported_ (as there is no standard followed  for exchanging data within the scripts). The scripts will do most of the work, and you get the output which will be the end result. Good idea to have GUI but I guess it will have issues when running on different systems (portability issues).

**Comment by qkaiser** [comment]
From what I've seen, there's a django web interface where you can enter a domain name. The tool query workers and return the results on the web page.

To get your server running:

`$ cd datasploit/core`
`$ mv osint/config_sample.py osing/config.py`
`$ python manage.py migrate`
`$ python manage.py runserver`

If you want to observer workers being called and do some debug:

`$ python manage.py celery worker`

Still a bit unstable but the GUI is there.

**Comment by zalfredo** [comment]
From what it looks like the GUI is in no way implemented beyond being able to display the page.

**Comment by upgoingstar** [comment]
Hi guys, 

Apologies for late reply. We have a GUI in place (however its a very basic one and renders the output in a tiled format on the page). 

We are using Django and Celery for that. In order to use that, please start your Django server in datasploit/core directory, as well as start the Celery service. 

once done, please head to 127.0.0.1/osint, and thats where the UI is running. 

Please be aware that this module is under work, and once this is fully working, we will include this in our documentation as well. 

Thank you.

**Comment by upgoingstar** [comment]
GUI is no more supported. Please go through new documentation to understand on how to setup tool. 

https://datasploit.github.io/datasploit/
