### ISSUE TITLE
https redirection on punkspider triggers exception

### ISSUE THREAD

**Issue by shaddai** [DataSploit/datasploit#5]
In the domain_checkpunkspider.py file, data is fetched on the punkspider website using the http protocol :
req= requests.post("http://www.punkspider.org/service/search/detail/" + reversed_domain)

unfortunately, the site can only be reached on https:
$ curl -I http://www.punkspider.org/service/search/detail/
HTTP/1.1 301 Moved Permanently
Date: Mon, 20 Jun 2016 14:50:43 GMT
Server: Apache/2.4.7 (Ubuntu)
Location: https://www.punkspider.org/service/search/detail/
Content-Type: text/html; charset=iso-8859-1

An error is triggered and in order to use this module you have to add the ", the verify=False" to the post request.
Why ? The punkspider.org website uses a certificate which chain of trust is incomplete which prevents the python module from querying it.

**Comment by upgoingstar** [comment]
Looks like program is getting me results without any changes. 

			[+] Checking PunkSpider
[+] Few vulnerabilities found at Punkspider
==>  xss
Method: GET
URL:
http://google.com/gwtn?u=%22%3E%3CScRipT%3Ealert%2831337%29%3C%2FScrIpT%3E
Param: u

----snipped----

Method: GET
URL:
http://google.com/gwtx?wsc=da&ei=lzH4SvXqMKKgiQShwdGCCw&wsi=%22%3E%3CScRipT%3Ealert%2831337%29%3C%2FScrIpT%3E&source=wax&whp=30&u=http%3A%2F%2Fprovidencia.blogspot.com&ct=pg1
Param: wsi

-----------------------------


Can you paste the exact error you are receiving at your end?

**Comment by SudhanshuC** [comment]
This could be because there are issues with the site's certificate chain (net::ERR_CERT_REVOKED). As chrome says "You cannot visit www.punkspider.org at the moment because this certificate has been revoked". So as the CERT is not trusted the requests library is not able to make a secure connection and hence you need to ignore it's verification (verify=False) for successfully fetching data. Check attached image.
![punkspider](https://cloud.githubusercontent.com/assets/2325647/16202964/ae45fc10-3735-11e6-916a-77b497209787.PNG)

**Comment by upgoingstar** [comment]
I have updated the same. @shaddai thanks buddy.

**Comment by shaddai** [comment]
You're welcome. I'm planning on using datasploit quite often, I may open other issues if I find bugs ;)

**Comment by upgoingstar** [comment]
Thats awesome, We will try to get them solved asap. Also soon, there will be a GUI to make it more useful. 

Also feel free to contribute, just in case :)
